"""Add is_ready field to Property model

Revision ID: c41773ae4774
Revises: d302adcb0fb8
Create Date: 2025-11-09 20:00:54.835009
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c41773ae4774'
down_revision = 'd302adcb0fb8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('is_ready', sa.Boolean(), nullable=False, comment='Whether property is ready for tenants or habitation'))
    op.create_index('idx_owner_ready', 'properties', ['owner_id', 'is_ready'], unique=False)
    op.create_index(op.f('ix_properties_is_ready'), 'properties', ['is_ready'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_properties_is_ready'), table_name='properties')
    op.drop_index('idx_owner_ready', table_name='properties')
    op.drop_column('properties', 'is_ready')
    # ### end Alembic commands ###
