"""Add Property model

Revision ID: d302adcb0fb8
Revises: 3bab1f45f28a
Create Date: 2025-11-09 19:46:22.643531
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd302adcb0fb8'
down_revision = '3bab1f45f28a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('properties',
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('property_name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('share_weight', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_owner_active', 'properties', ['owner_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_properties_is_active'), 'properties', ['is_active'], unique=False)
    op.create_index(op.f('ix_properties_owner_id'), 'properties', ['owner_id'], unique=False)
    op.drop_table('administrators')
    op.create_index(op.f('ix_access_requests_responded_by_admin_id'), 'access_requests', ['responded_by_admin_id'], unique=False)
    op.create_index(op.f('ix_access_requests_status'), 'access_requests', ['status'], unique=False)
    op.create_index(op.f('ix_access_requests_submitted_at'), 'access_requests', ['submitted_at'], unique=False)
    op.create_index(op.f('ix_access_requests_user_telegram_id'), 'access_requests', ['user_telegram_id'], unique=False)
    op.drop_index(op.f('ix_contribution_ledgers_service_period_id_user_id'), table_name='contribution_ledgers')
    op.drop_index(op.f('ix_expense_ledgers_service_period_id_paid_by_user_id'), table_name='expense_ledgers')
    op.drop_index(op.f('ix_expense_ledgers_service_period_id_payment_type'), table_name='expense_ledgers')
    op.drop_index(op.f('ix_service_charges_service_period_id_user_id'), table_name='service_charges')
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    op.drop_index(op.f('ix_utility_readings_service_period_id_meter_name'), table_name='utility_readings')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_utility_readings_service_period_id_meter_name'), 'utility_readings', ['service_period_id', 'meter_name'], unique=False)
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.create_index(op.f('ix_service_charges_service_period_id_user_id'), 'service_charges', ['service_period_id', 'user_id'], unique=False)
    op.create_index(op.f('ix_expense_ledgers_service_period_id_payment_type'), 'expense_ledgers', ['service_period_id', 'payment_type'], unique=False)
    op.create_index(op.f('ix_expense_ledgers_service_period_id_paid_by_user_id'), 'expense_ledgers', ['service_period_id', 'paid_by_user_id'], unique=False)
    op.create_index(op.f('ix_contribution_ledgers_service_period_id_user_id'), 'contribution_ledgers', ['service_period_id', 'user_id'], unique=False)
    op.drop_index(op.f('ix_access_requests_user_telegram_id'), table_name='access_requests')
    op.drop_index(op.f('ix_access_requests_submitted_at'), table_name='access_requests')
    op.drop_index(op.f('ix_access_requests_status'), table_name='access_requests')
    op.drop_index(op.f('ix_access_requests_responded_by_admin_id'), table_name='access_requests')
    op.create_table('administrators',
    sa.Column('telegram_id', sa.VARCHAR(length=50), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('active', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('telegram_id')
    )
    op.drop_index(op.f('ix_properties_owner_id'), table_name='properties')
    op.drop_index(op.f('ix_properties_is_active'), table_name='properties')
    op.drop_index('idx_owner_active', table_name='properties')
    op.drop_table('properties')
    # ### end Alembic commands ###
