"""Initial migration: create ClientRequest and Administrator tables

Revision ID: e2d56fdbda32
Revises:
Create Date: 2025-11-04 16:34:52.607297
"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'e2d56fdbda32'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'administrators',
        sa.Column('telegram_id', sa.String(length=50), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=True),
        sa.Column('active', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('telegram_id'),
    )
    op.create_table(
        'client_requests',
        sa.Column('client_telegram_id', sa.String(length=50), nullable=False),
        sa.Column('request_message', sa.Text(), nullable=False),
        sa.Column(
            'status',
            sa.Enum('PENDING', 'APPROVED', 'REJECTED',
                    name='requeststatus', native_enum=False),
            nullable=False,
        ),
        sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('admin_telegram_id', sa.String(length=50), nullable=True),
        sa.Column('admin_response', sa.Text(), nullable=True),
        sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index('idx_status', 'client_requests', ['status'],
                    unique=False)
    op.create_index('idx_submitted_at', 'client_requests', ['submitted_at'],
                    unique=False)
    op.create_index(
        op.f('ix_client_requests_client_telegram_id'),
        'client_requests',
        ['client_telegram_id'],
        unique=False,
    )
    op.create_index(
        op.f('ix_client_requests_status'),
        'client_requests',
        ['status'],
        unique=False,
    )
    op.create_index(
        op.f('ix_client_requests_submitted_at'),
        'client_requests',
        ['submitted_at'],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_client_requests_submitted_at'), table_name='client_requests')
    op.drop_index(op.f('ix_client_requests_status'), table_name='client_requests')
    op.drop_index(op.f('ix_client_requests_client_telegram_id'), table_name='client_requests')
    op.drop_index('idx_submitted_at', table_name='client_requests')
    op.drop_index('idx_status', table_name='client_requests')
    op.drop_table('client_requests')
    op.drop_table('administrators')
    # ### end Alembic commands ###
